### ISSUE TITLE
need update 

### ISSUE THREAD

**Issue by cxwx** [akira-okumura/PyTeVCat#2]
Unknown source type name found:  PWN/TeV Halo

**Comment by akira-okumura** [comment]
Thank you for the report. I cannot run PyTeVCat on my machine at the moment because the latest ROOT looks to be incompatible with PyTeVCat, and therefore I need fix another place before adding "PWN/TeV Halo". Can you please manually edit `source_type_names` in `tevcat_all.py` in your site-package directory?

**Comment by akira-okumura** [comment]
Fixed in v1.3.1. It will show a few warning messages, but it is due to inconsistency in the original TeVCat JSON file.

**Comment by cxwx** [comment]
thanks, I just wake up today
